### ISSUE TITLE
mailbox.log and tracelog being filled up with errors

### ISSUE THREAD

**Issue by Kordolio** [Z-Hub/Z-Push#41]
Hello,
Thank you for continuing with z-push.
I installed my z-push on a separate Debian server. Have php8.2. Everything is working perfect, with one big exception - the mailbox.log on the Zimbra (tried 9 and now 10) are being filled with entries like:

2024-01-02 13:44:21,085 WARN  [qtp758013696-5095:https://xxxx.xxxx.xx/service/soap/] [name=xxxxxxx;mid=3;ip=xxxxxxxxxxxxxxxx;port=32940;ua=Outlook/16.0 (16.0.5401.1>
com.zimbra.cs.account.AccountServiceException: no such account: 0
        at com.zimbra.cs.account.AccountServiceException.NO_SUCH_ACCOUNT(AccountServiceException.java:221) ~[zimbrastore.jar:10.0.5_GA_0423]
        at com.zimbra.soap.DocumentHandler.getServer(DocumentHandler.java:439) ~[zimbrastore.jar:10.0.5_GA_0423]
        at com.zimbra.cs.service.mail.MailDocumentHandler.proxyRequest(MailDocumentHandler.java:136) ~[zimbrastore.jar:10.0.5_GA_0423]
        at com.zimbra.cs.service.mail.MailDocumentHandler.proxyRequest(MailDocumentHandler.java:117) ~[zimbrastore.jar:10.0.5_GA_0423]
        at com.zimbra.cs.service.mail.MailDocumentHandler.proxyIfNecessary(MailDocumentHandler.java:63) ~[zimbrastore.jar:10.0.5_GA_0423]
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:637) ~[zimbrastore.jar:10.0.5_GA_0423]
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:471) ~[zimbrastore.jar:10.0.5_GA_0423]
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:278) ~[zimbrastore.jar:10.0.5_GA_0423]
        at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:308) ~[zimbrastore.jar:10.0.5_GA_0423]
        at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:217) ~[zimbrastore.jar:10.0.5_GA_0423]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[servlet-api-3.1.jar:3.1.0]
        at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:214) ~[zimbrastore.jar:10.0.5_GA_0423]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[servlet-api-3.1.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292) ~[websocket-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:175) ~[zimbrastore.jar:10.0.5_GA_0423]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54) ~[zimbrastore.jar:10.0.5_GA_0423]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59) ~[zimbrastore.jar:10.0.5_GA_0423]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47) ~[zimbrastore.jar:10.0.5_GA_0423]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107) ~[zimbrastore.jar:10.0.5_GA_0423]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:125) ~[zimbrastore.jar:10.0.5_GA_0423]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:118) ~[zimbrastore.jar:10.0.5_GA_0423]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:487) ~[jetty-servlets-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:336) ~[jetty-servlets-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:301) ~[jetty-servlets-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571) ~[jetty-security-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]

The files grow to over 500 GB within a relatively short period of time.
Thank you very much in advance for support!

**Comment by matidau** [comment]
Hey @Kordolio

Have you reached out to the Zimbra Backend project?

https://sourceforge.net/projects/zimbrabackend/support

Cheers,
Mat

**Comment by Kordolio** [comment]
Hello,
Thank you, but I do not think it is the Backend that causes the problem since the backend has not been updated for some time now and it used to work. Besides it is working for others, so I did not go that way :-)

**Comment by matidau** [comment]
I don't really directly support the Zimbra backend, unless there is an error message inside Z-Push logs or something on the client side. 

What you have shown me in the error logs points to a problem with the Backend calling for account 0 that doesn't exist. I'm not familiar with Zimbra so not sure if this is an expected output. 

As recently as October there seemed to be a problem with Zimbra 9 and/or 10, likely unrelated to your issue, but maybe they can help with your issue.

https://sourceforge.net/p/zimbrabackend/bugs/101/#c562

**Comment by Kordolio** [comment]
OK, added it there as well, thank you. Any other ideas?

**Comment by matidau** [comment]
Have you checked in the Z-Push logs to see if there is more information on why account 0 is being called?

**Comment by Kordolio** [comment]
Well, looks like you were right, I have these:
/z-push/backend/zimbra/zimbra.php:2178 Undefined array key "rid" (2)
Zimbra->ProcessZimbraSmartFolderRecursive(): Possible orphaned share - Folder [Files shared with me] has zid [0] but no owner - Folder should be removed from the Web client
So it looks like the bug you mentioned.
Any chance they will correct it?

**Comment by matidau** [comment]
That does seem to point in that direction. Complete fluke, that it is the same issue. I wanted to illustrate that work was being done for Zimbra 9 & 10.

If you have a look at the releases on Sourceforge, one occurs every year or two, so I would say that there is a good chance that it will be fixed in the next release of the Backend.

**Comment by matidau** [comment]
Looks like you have gotten support from the Zimbra Backend project.

Will close this off now.

Cheers,
Mat
